# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mf.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from monitor.checklabel import ClickableLabel


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1321, 697)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(130, 110, 381, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        # 使用ClickableLabel代替QLabel
        self.video1 = ClickableLabel(self.frame)
        self.video1.setGeometry(QtCore.QRect(0, 0, 381, 201))
        self.video1.setObjectName("video1")

        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(130, 59, 151, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.frame_6 = QtWidgets.QFrame(Dialog)
        self.frame_6.setGeometry(QtCore.QRect(290, 60, 221, 41))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.carnum = QtWidgets.QLabel(self.frame_6)
        self.carnum.setGeometry(QtCore.QRect(0, 0, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.carnum.setFont(font)
        self.carnum.setStyleSheet("color:red\n"
"")
        self.carnum.setObjectName("carnum")

        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(260, 10, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")

        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(130, 320, 981, 321))
        self.groupBox.setObjectName("groupBox")

        self.screenshotButton = QtWidgets.QPushButton(Dialog)
        self.screenshotButton.setGeometry(QtCore.QRect(520, 280, 100, 30))
        self.screenshotButton.setObjectName("screenshotButton")

        self.nwButton = QtWidgets.QPushButton(Dialog)
        self.nwButton.setGeometry(QtCore.QRect(640, 280, 101, 31))
        self.nwButton.setObjectName("nwButton")

        self.swButton_2 = QtWidgets.QRadioButton(Dialog)
        self.swButton_2.setGeometry(QtCore.QRect(530, 180, 96, 24))
        self.swButton_2.setObjectName("swButton_2")

        self.swButton_1 = QtWidgets.QRadioButton(Dialog)
        self.swButton_1.setGeometry(QtCore.QRect(530, 140, 96, 24))
        self.swButton_1.setObjectName("swButton_1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.video1.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "东门-车流流量:"))
        self.carnum.setText(_translate("Dialog", "0"))
        self.title.setText(_translate("Dialog", "人车流量监控系统"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.screenshotButton.setText(_translate("Dialog", "Screenshot"))
        self.nwButton.setText(_translate("Dialog", "new"))
        self.swButton_2.setText(_translate("Dialog", "yuan2"))
        self.swButton_1.setText(_translate("Dialog", "yuan1"))

